// Generated by ts-to-zod
import { z } from "zod";

export const organizationModelSchema = z.object({
    name: z.string().min(2).max(50),
    id: z.string(),
    description: z.string().nullable(),
    stateId: z.number(),
    currencyId: z.number(),
    timeZoneId: z.number(),
    inventoryStartDate: z.date(),
    languageId: z.number().nullable(),
    industryCategoryId: z.number().nullable(),
    fiscalYearPatternId: z.number().nullable(),
    ownerId: z.string(),
    address: z.string().nullable(),
    zipCode: z.string().nullable(),
    createdAt: z.date(),
    updatedAt: z.date()
});

export const organizationCreateInputSchema = organizationModelSchema.omit({ "id": true, "createdAt": true, "updatedAt": true });

export const organizationUpdateInputSchema = organizationModelSchema.partial();

export const organizationWhereUniqueInputSchema = z.union([z.object({
        id: z.string()
    }), z.object({
        name_ownerId: z.object({
            name: z.string(),
            ownerId: z.string()
        })
    })]);

export const organizationWhereInputSchema = organizationModelSchema.partial();
