// Generated by ts-to-zod
import { z } from "zod";
import { UserRoleStatus } from "./types.js";

export const userRoleStatusSchema = z.enum(UserRoleStatus);

export const roleModelSchema = z.object({
  name: z.string(),
  id: z.string(),
  description: z.string().optional().nullable(),
  organizationId: z.string(),
  createdById: z.string(),
  isSystem: z.boolean(),
  status: userRoleStatusSchema,
  priority: z.number(),
  createdAt: z.date(),
  updatedAt: z.date(),
  expiresAt: z.date().optional().nullable(),
});

export const roleCreateInputSchema = roleModelSchema.omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const roleCreateBodySchema = roleModelSchema.omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  createdById: true,
});

export const roleUpdateInputSchema = roleModelSchema.partial();

export const roleWhereUniqueInputSchema = z.union([
  z.object({
    id: z.string(),
  }),
  z.object({
    organizationId_name: z.object({
      name: z.string(),
      organizationId: z.string(),
    }),
  }),
]);

export const roleWhereInputSchema = roleModelSchema.partial();

export const roleOrderByInputSchema = z.union([
  z.record(z.any(), z.union([z.literal("asc"), z.literal("desc")])),
  z.undefined(),
]);

export const rolePermissionCreateManyInputSchema = z.array(
  z.object({
    roleId: z.string(),
    permissionId: z.string(),
  })
);
