/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */

export type _36EnumsResourceName = typeof _36EnumsResourceName[keyof typeof _36EnumsResourceName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _36EnumsResourceName = {
  USER: 'USER',
  ROLE: 'ROLE',
  ITEM: 'ITEM',
  INVOICE: 'INVOICE',
  CUSTOMER: 'CUSTOMER',
  SUPPLIER: 'SUPPLIER',
  PURCHASE_ORDER: 'PURCHASE_ORDER',
  SALES_ORDER: 'SALES_ORDER',
  WAREHOUSE: 'WAREHOUSE',
  ORGANIZATION: 'ORGANIZATION',
  REPORT: 'REPORT',
} as const;
