/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */

export type _36EnumsActionName = typeof _36EnumsActionName[keyof typeof _36EnumsActionName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _36EnumsActionName = {
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  EXPORT: 'EXPORT',
  IMPORT: 'IMPORT',
  SHARE: 'SHARE',
  ARCHIVE: 'ARCHIVE',
  RESTORE: 'RESTORE',
} as const;
