/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */

export type _36EnumsOtpType = typeof _36EnumsOtpType[keyof typeof _36EnumsOtpType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _36EnumsOtpType = {
  SIGN_UP: 'SIGN_UP',
  LOGIN: 'LOGIN',
  FORGET_PASSWORD: 'FORGET_PASSWORD',
} as const;
