/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */

export type GetOwnedOrganizations200Item = {
  zipCode: string;
  address: string;
  ownerId: string;
  fiscalYearPatternId: string;
  industryCategoryId: string;
  languageId: string;
  inventoryStartDate: string;
  timeZoneId: string;
  currencyId: string;
  stateId: string;
  description: string;
  name: string;
  updatedAt: string;
  createdAt: string;
  id: string;
};
