/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */
import type { _36EnumsResourceName } from './_36EnumsResourceName';

export type GetPermissionMatrix200ResourcesItem = {
  description: string;
  name: _36EnumsResourceName;
  id: string;
};
