/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */

export type GetPermissionMatrix200PermissionsItem = {
  isDangerous: boolean;
  category: string;
  resourceId: string;
  actionId: string;
  description: string;
  id: string;
};
