/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */
import type { _36EnumsActionName } from './_36EnumsActionName';

export type GetPermissionMatrix200ActionsItem = {
  description: string;
  name: _36EnumsActionName;
  id: string;
};
