/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */
import type { GetPermissionMatrix200PermissionsItem } from './getPermissionMatrix200PermissionsItem';
import type { GetPermissionMatrix200ResourcesItem } from './getPermissionMatrix200ResourcesItem';
import type { GetPermissionMatrix200ActionsItem } from './getPermissionMatrix200ActionsItem';

export type GetPermissionMatrix200 = {
  permissions: GetPermissionMatrix200PermissionsItem[];
  resources: GetPermissionMatrix200ResourcesItem[];
  actions: GetPermissionMatrix200ActionsItem[];
};
