/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */

export type GetRolePermissions200Item = {
  permissionId: string;
  id: string;
};
