/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */

export type GetStates200ItemCountryTimezonesItem = {
  offset: string;
  name: string;
  id: string;
};
