/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */
import type { GetStates200ItemCountryTimezonesItem } from './getStates200ItemCountryTimezonesItem';

export type GetStates200ItemCountry = {
  timezones: GetStates200ItemCountryTimezonesItem[];
};
