/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */
import type { GetStates200ItemCountry } from './getStates200ItemCountry';

export type GetStates200Item = {
  country: GetStates200ItemCountry;
  name: string;
  id: string;
};
