/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */
import type { PickRoleModelExcludeKeyofRoleModelIdOrCreatedAtOrUpdatedAtOrCreatedById } from './pickRoleModelExcludeKeyofRoleModelIdOrCreatedAtOrUpdatedAtOrCreatedById';

/**
 * Construct a type with the properties of T except for those in type K.
 */
export type OmitRoleModelIdOrCreatedAtOrUpdatedAtOrCreatedById = PickRoleModelExcludeKeyofRoleModelIdOrCreatedAtOrUpdatedAtOrCreatedById;
