/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */
import type { OrganizationFormData200IndustryCategoriesItem } from './organizationFormData200IndustryCategoriesItem';
import type { OrganizationFormData200CurrenciesItem } from './organizationFormData200CurrenciesItem';
import type { OrganizationFormData200FiscalYearPatternItem } from './organizationFormData200FiscalYearPatternItem';
import type { OrganizationFormData200TimezonesItem } from './organizationFormData200TimezonesItem';
import type { OrganizationFormData200LanguagesItem } from './organizationFormData200LanguagesItem';
import type { OrganizationFormData200CountriesItem } from './organizationFormData200CountriesItem';

export type OrganizationFormData200 = {
  industryCategories: OrganizationFormData200IndustryCategoriesItem[];
  currencies: OrganizationFormData200CurrenciesItem[];
  fiscalYearPattern: OrganizationFormData200FiscalYearPatternItem[];
  timezones: OrganizationFormData200TimezonesItem[];
  languages: OrganizationFormData200LanguagesItem[];
  countries: OrganizationFormData200CountriesItem[];
};
