/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickOrganizationModelExcludeKeyofOrganizationModelIdOrCreatedAtOrUpdatedAtOrOwnerId {
  /**
   * The name of the organization.
   * @minLength 2
   * @maxLength 50
   */
  name: string;
  /**
   * The name of the organization.
   * @minLength 2
   * @maxLength 250
   */
  description?: string;
  stateId: string;
  currencyId: string;
  timeZoneId: string;
  inventoryStartDate: string;
  languageId?: string;
  industryCategoryId?: string;
  fiscalYearPatternId?: string;
  address?: string;
  zipCode?: string;
}
