/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */
import type { UserRoleStatus } from './userRoleStatus';

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickRoleModelExcludeKeyofRoleModelIdOrCreatedAtOrUpdatedAtOrCreatedById {
  expiresAt?: string;
  name: string;
  description?: string;
  organizationId: string;
  isSystem: boolean;
  status: UserRoleStatus;
  priority: number;
}
