/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */
import type { _36EnumsOtpType } from './_36EnumsOtpType';

export type RequestOtpBody = {
  otpType: _36EnumsOtpType;
  identifier: string;
};
