/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */
import type { PickRoleCreateInputExcludeKeyofRoleCreateInputCreatedById } from './pickRoleCreateInputExcludeKeyofRoleCreateInputCreatedById';

/**
 * Base input type for updating a role.
Similar to creation, but excludes createdById.
 */
export type RoleUpdateInput = PickRoleCreateInputExcludeKeyofRoleCreateInputCreatedById;
