/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */
import type { RolePermissionCreateManyInputItem } from './rolePermissionCreateManyInputItem';

/**
 * Represents multiple role-permission associations.
 */
export type RolePermissionCreateManyInput = RolePermissionCreateManyInputItem[];
