/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */
import type { PickRoleCreateInputExcludeKeyofRoleCreateInputCreatedById } from './pickRoleCreateInputExcludeKeyofRoleCreateInputCreatedById';
import type { RoleCreateBodyAllOf } from './roleCreateBodyAllOf';

export type RoleCreateBody = PickRoleCreateInputExcludeKeyofRoleCreateInputCreatedById & RoleCreateBodyAllOf;
