/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */

export type UpdateRole200 = {
  priority: number;
  isSystem: boolean;
  createdById: string;
  organizationId: string;
  description: string;
  name: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
  id: string;
};
