/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */

export type UserRoleStatus = typeof UserRoleStatus[keyof typeof UserRoleStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRoleStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
} as const;
