/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @khaled/ims-server
 * OpenAPI spec version: 1.3.0
 */

export type UserResponseTypeIdentifierType = typeof UserResponseTypeIdentifierType[keyof typeof UserResponseTypeIdentifierType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseTypeIdentifierType = {
  email: 'email',
  phone: 'phone',
} as const;
